# Generated by Django 5.0.6 on 2024-07-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rhetorical', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database',
            new_name='Rhetorical_Database',
        ),
    ]
