# Generated by Django 5.0.6 on 2024-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo_Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Database',
        ),
    ]
