# Generated by Django 5.0.6 on 2024-07-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database',
            new_name='Mental_Health_Database',
        ),
    ]
