# Generated by Django 5.0.6 on 2024-07-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifeStyle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database',
            new_name='Life_Style_Database',
        ),
    ]
